### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by Namek** [halohalospecial/atom-elmjutsu#88] opened 2017-08-14 13:17 UTC
[Enter steps to reproduce:]

1. Enable Hyperclick
2. CTRL click on type name used somewhere

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [elmjutsu](https://github.com/halohalospecial/atom-elmjutsu) package 5.6.2

### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At C:\Users\Namek\.atom\packages\elmjutsu\lib\go-to.js:84

TypeError: Cannot read property 'getPath' of undefined
    at GoTo.storeJumpPoint (/packages/elmjutsu/lib/go-to.js:84:63)
    at Object.callback (/packages/elmjutsu/lib/hyperclick-provider.js:27:23)
    at t.default._confirmSuggestion (/packages/hyperclick/index.js:1:157838)
    at t.default._onMouseDown (/packages/hyperclick/index.js:1:158868)
```

### Commands

```
     -2:44.9.0 core:page-up (input.hidden-input)
     -2:44.1.0 intentions:highlight (input.hidden-input)
     -2:44 pane:show-next-item (input.hidden-input)
  2x -2:41.9.0 core:move-down (input.hidden-input)
     -2:31 timecop:view (input.hidden-input)
     -2:14.7.0 core:close (div.timecop.pane-item.native-key-bindings)
  5x -1:58.8.0 core:page-down (input.hidden-input)
  5x -1:55 core:page-up (input.hidden-input)
     -1:49.4.0 intentions:highlight (input.hidden-input)
     -1:49.3.0 core:close (input.hidden-input)
 16x -0:12 intentions:highlight (input.hidden-input)
```

### Non-Core Packages

```
angular-jonpapa-snippets 0.7.0 
atom-beautify 0.30.4 
autoclose-html 0.23.0 
bluebliss 0.1.0 
build-gradle 0.6.0 
busy-signal 1.4.3 
color-picker 2.2.5 
editorconfig 2.2.2 
elm-format 2.2.0 
elmjutsu 5.6.2 
emmet 2.4.3 
file-icons 2.1.10 
git-history 3.3.0 
git-log 0.4.1 
git-plus 7.9.3 
git-status 0.3.4 
goto 1.8.3 
highlight-selected 0.13.1 
hyperclick 0.1.3 
intentions 1.1.5 
language-diff 0.7.0 
language-elm 1.5.0 
language-glsl 2.0.1 
language-gradle 0.0.3 
laravel-4-snippets 0.1.0 
last-cursor-position 0.9.2 
linter 2.2.0 
linter-elm-make 0.23.7 
linter-ui-default 1.6.4 
merge-conflicts 1.4.5 
minimap 4.29.6 
minimap-highlight-selected 4.6.1 
nucleus-dark-ui 0.12.3 
pain-split 1.4.0 
pigments 0.40.2 
plantuml-viewer 0.7.2 
release-notes 0.53.0 
script 3.15.0 
set-syntax 0.3.2 
smart-tags 0.1.5 
sync-settings 0.8.2 
text-manipulation 0.6.0 
trailing-spaces 0.4.0 
```

**Comment by Namek** [comment] 2017-08-14 13:22
Unfortunately, can't reproduce anymore.

**Comment by kaskelotti** [comment] 2018-03-19 18:28
There has been a bunch of updates to Atom, Electron framework and elmjutsu since this was created. Since it hasn't been reproducible, I vote for closing the issue.

**Closed** 2018-03-27 02:54 UTC
